go.mod
The patch version should not be included in the minimum go version in go.mod.
=> fixes the go.mod spec

.github/workflows/build.yml, .goreleaser.yaml, README.md, authorization_code.go, cmd/authorization_code_cfg.go, cmd/authorization_code_cmd.go, cmd/oidc-cli.go, go.mod, oidc.go
* changes cli interface to use subcommands
This is the first step to bringing more structure to the CLI and
breaking things down into sub commands and keeping the parsing of them
separate we should have an easier time adding validation and tests.
References:
* https://eli.thegreenplace.net/2020/testing-flag-parsing-in-go-programs/
* https://www.janekbieser.dev/posts/cli-app-with-subcommands-in-go/
=> Subcommands

authorization_code.go, cmd/authorization_code_cfg.go, cmd/authorization_code_cfg_test.go, cmd/client_credentials_cfg_test.go, oidc.go, oidc_test.go
This adds a command-line argument --pkce to the authorization_code command. When provided it will create a code_verifier and code_challenge and add these to the respective calls to the authorization server.
Providing --pkce without providing --client-secret is considered valid.
=> adds pkce support to authorization_code flow

browser.go, browser_darwin.go, browser_linux.go, browser_unsupported.go, browser_windows.go, oidc.go
Both Windows and Mac open the browser automatically for the auth code flow
=> supports automatically opening browser in windows

authorization_code.go, cmd/authorization_code_cfg.go, oidc.go, oidc_config.go
This adds support for --custom arguments to the authorization_code flow, which enables users to provide additional arguments to the authorization request as needed.
=> adds custom arguments for authorization_code

cmd/introspect_cfg.go, cmd/introspect_cfg_test.go, cmd/oidc-cli.go, introspect.go, introspection_request.go, introspection_response.go
Adds foundational support for token introspection as a new subcommand. Allows passing a token on the command-line and outputs the parsed response.
Accepts the following arguments:
```
❯ ./oidc-cli introspect -h
Usage of introspect:
-bearer-token string
bearer token for authorization (required unless client secret is provided)
-client-id string
set client ID (required)
-client-secret string
set client secret (required unless bearer token is provided)
-discovery-url string
override discovery url
-issuer string
set issuer url (required)
-token string
token to be introspected (required)
-token-type string
token type hint (e.g. access_token (default "access_token")
-token-url string
override token url
```
Known limitations:
* limited error handling
* missing tests
* non-standard claims in …
=> feat: support token introspection

.gitignore, authorization_request.go, callback_endpoint.go
This parses the callback-uri parameter to determine the address and port for the http server as well as the path that it will listen on for receiving the callback request. Before starting the server, this checks that the requested combination of address and port is free.
Closes #26
=> feat: allows the user to customize the callback url

authorization_code.go, authorization_request.go, client_credentials.go, cmd/authorization_code_cfg.go, cmd/authorization_code_cfg_test.go, cmd/oidc-cli.go, introspect.go, introspection_request.go, oidc_config.go, token_request.go
This adds the ```--skip-tls-verify``` argument which will skip TLS certificate verification. This is particularly useful when running the cli against a development instance of an authorization server which doesn't have properly signed certificates. The default value of ```false``` will keep TLS verification enabled unless explicitly requested otherwise.
=> feat: adds option to skip tls certificate verification

token_request.go
Stops printing the body of the request to the token endpoint to avoid showing sensitive information like the client secret. We can add support for debug/verbose output or add obfuscation of the secret later, this is just a quick fix to stop showing by default.
=> removes output that can show secrets

README.md, cmd/authorization_code_cfg_test.go, cmd/oidc-cli.go, cmd/token_refresh_cfg.go, cmd/token_refresh_cfg_test.go, token_refresh.go, token_request.go
Implements token_refresh command to perform a token refresh. Token refresh expects a refresh token as input, either provided with a command-line parameter or through stdin, while the output is in the same format as other commands.
This also simplifies the implementation of the token request and brings it in line with the authorization request implementation in terms of using gorilla/schema for constructing the request based on the provided attributes.
=> feat: implements token refresh flow and simplifies token requests

cmd/authorization_code_cfg.go, cmd/authorization_code_cfg_test.go, cmd/client_credentials_cfg.go, cmd/client_credentials_cfg_test.go, cmd/global_cfg.go, cmd/global_cfg_test.go, cmd/introspect_cfg.go, cmd/introspect_cfg_test.go, cmd/oidc-cli.go, cmd/token_refresh_cfg.go, cmd/token_refresh_cfg_test.go
This adds the ability for some flags to be provided before the subcommand. This makes it easier to work with aliases, for example when you'd like to have an alias for each instance of an authorization server or for different client configurations.
Known limitations:
* Global flags are not printed in the output of ```oidc-cli help```
* Global flags are not added dynamically to each subcommand.
The limitations could probably be resolved by providing a way to inject the global flagset into the various subcommands' parsing functions as well as into the usage function.
=> feat: adds support for global flags

cmd/introspect_cfg.go, cmd/introspect_cfg_test.go, introspect.go, introspection_request.go, introspection_response.go
Adds a `--response-format` flag to the introspect command. This flag can be used to indicated the desired format of the response, in particular to choose between json and a JWT. The default value is `json`. The value required to retrieve a JWT is dependent on the implementation of the authorization server that is used (e.g. for Ping Federate it is `token-introspection+jwt` while for Keycloak it is just `jwt`).
=> feat: adds flag for introspection response format

authorization_code.go, client_credentials.go, cmd/authorization_code_cfg.go, cmd/client_credentials_cfg.go, cmd/introspect_cfg.go, cmd/oidc-cli.go, cmd/token_refresh_cfg.go, discovery.go, introspect.go, introspection_request.go, oidc_config.go, par_request.go, token_refresh.go, token_request.go
Adds identification of supported authentication methods during discovery. Also adds the option of indicating the desired authentication method using the `--auth-method` command-line argument. 
Known limitations:
* Currently, only support for `client_secret_basic` and `client_secret_post` has been implemented.
=> feat: adds possibility to indicate desired authentication method

.gitignore, authorization_code.go, cmd/authorization_code_cfg.go, cmd/authorization_code_cfg_test.go, go.mod, go.sum, oidc_config.go, pkg/crypto/dpop.go, pkg/crypto/dpop_test.go, pkg/crypto/pem.go, pkg/crypto/pem_test.go, pkg/crypto/pkce.go, pkg/crypto/pkce_test.go, token_request.go
This PR adds a `--dpop` command-line argument that - when present - will add a DPoP header to a token request that is made during an authorization code flow execution. This implements the client-part of RFC9449. This feature is most useful in combination with a resource server that expects to receive "DPoP-Bound Access Tokens".
In order to generate a "DPoP Proof" the user will also be required to provide a private/public keypair using `--private-key` and `--public-key` command-line arguments. DPoP does not allow using symmetric algorithms for signing the DPoP Proof.
=> feature: implements support for dpop (RFC9449)

authorization_request.go, pkg/webflow/browser.go, pkg/webflow/browser_darwin.go, pkg/webflow/browser_linux.go, pkg/webflow/browser_test.go, pkg/webflow/browser_unsupported.go, pkg/webflow/browser_windows.go
This pull request refactors the browser-related code to enhance extensibility and testability, while also introducing comprehensive unit tests for the new functionality. The most important changes include replacing the `SystemBrowser` with a more flexible `Browser` interface, updating platform-specific browser opening functions to support dependency injection, and adding unit tests to validate the behavior of the new implementation.
* [`authorization_request.go`](diffhunk://#diff-09ffd35a35d1eeba724e5aa9fd69d5bff3146196dce8ef43858450387f55419dL82-R82): Replaced `webflow.NewSystemBrowser()` with `webflow.NewBrowser()` to use the new `Browser` interface, enabling greater flexibility in browser implementations.
* [`pkg/webflow/browser.go`](diffhunk://#diff-2c89f844a742eb5e48f5f3f3dc9c06ed90fc …
=> feat: add test coverage to browser.go

pkg/webflow/callback.go, pkg/webflow/callback_test.go
This pull request refactors the `CallbackServer` implementation in `pkg/webflow/callback.go` to improve testability, simplify template handling, and enhance error management. It also introduces comprehensive unit tests in `pkg/webflow/callback_test.go` to ensure the reliability of the `CallbackServer` functionality.
* Added a `listen` field to the `CallbackServer` struct to allow dependency injection for network listeners, improving testability.
* Replaced inline template parsing in `handleCallback` with pre-parsed templates (`successTmpl` and `errorTmpl`), reducing redundancy and improving performance. [[1]](diffhunk://#diff-d7db9dba83ecf87a72402b78285d26d39c2f549f62eaba5fedcc350b25617bd6R24-R28) [[2]](diffhunk://#diff-d7db9dba83ecf87a72402b78285d26d39c2f549f62eaba5fedcc350b25617bd6L93-R1 …
=> feat: add test coverage to callback.go

.goreleaser.yaml, README.md, authorization_code.go, authorization_request.go, client.go, client_credentials.go, cmd/authorization_code_cfg.go, cmd/authorization_code_cfg_test.go, cmd/client_credentials_cfg.go, cmd/client_credentials_cfg_test.go, cmd/global_cfg.go, cmd/global_cfg_test.go, cmd/introspect_cfg.go, cmd/introspect_cfg_test.go, cmd/oidc-cli.go, cmd/token_refresh_cfg.go, cmd/token_refresh_cfg_test.go, go.mod, introspect.go, introspection_request.go, oidc_config.go, par_request.go, pkg/webflow/callback.go, pkg/webflow/callback_test.go, token_refresh.go, token_request.go
This pull request updates the project name and repository references from "vigilant-dollop" to "oidc-cli" across multiple files. It includes changes to documentation, configuration files, and import paths in the codebase to ensure consistency with the new project name.
* Updated the project name in `README.md` from "vigilant-dollop" to "oidc-cli" and replaced references to the old repository URL with the new one. [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L1-R1) [[2]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L28-R32)
* Updated `.goreleaser.yaml` to reflect the new repository name and homepage for Homebrew and Scoop package configurations.
* Changed all import paths in Go files to use …
=> chore: rename vigilant-dollop to oidc-cli

Makefile
This pull request introduces a `Makefile` to streamline common development tasks for the `oidc-cli` project. The `Makefile` provides targets for building, testing, linting, cleaning, and generating test coverage reports.
Key additions:
* [`Makefile`](diffhunk://#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R1-R41): Added targets to automate tasks including `help`, `test`, `build`, `lint`, `clean`, and `coverage`. Each target is designed to simplify developer workflows, such as running tests (`test`), building the binary (`build`), and cleaning up artifacts (`clean`).
=> feat: add Makefile for build and test automation

.goreleaser.yaml
Migrates away from the deprecated `brew` Formula configuration and uses `homebrew_casks` instead.
=> feat: update goreleaser configuration for Homebrew casks

.goreleaser.yaml
Cause the cask to conflict with the deprecated formula to help the user understand there should only be the cask.
=> chore: improve homebrew migration

httpclient/authorization_code.go, httpclient/authorization_code_test.go, webflow/callback.go, webflow/callback_test.go
This pull request implements state parameter validation to enhance security against CSRF attacks in the OAuth 2.0 authorization code flow. It also updates the relevant tests and callback handling logic to support and verify this new functionality. Below are the most important changes grouped by theme:
- Added state parameter validation in `ExecuteAuthorizationCodeRequest` to ensure the state in the callback response matches the request, preventing CSRF attacks (`httpclient/authorization_code.go`, [httpclient/authorization_code.goR156-R167](diffhunk://#diff-b86308a31dee8f140fd458bdd57b211cb87862557517c74404ddbab29c5424f8R156-R167)).
- Updated `CallbackResponse` to include the `State` field, and modified the callback handler to parse the `state` parameter from the query string …
=> feat: add state validation to auth code flow

webflow/callback.go, webflow/callback_test.go
Potential fix for [https://github.com/jentz/oidc-cli/security/code-scanning/2](https://github.com/jentz/oidc-cli/security/code-scanning/2)
To fix this vulnerability, user-controlled data must be properly escaped before being rendered in the HTTP response. The best way to do this in Go is to use the `html/template` package instead of `text/template` for rendering HTML responses. The `html/template` package automatically escapes data when rendering, preventing XSS. 
**Steps to fix:**
- Change the import from `text/template` to `html/template` in `webflow/callback.go`.
- Ensure that all templates (`s.errorTmpl`, `s.successTmpl`) are created using `html/template.New(...)` or `template.ParseFS(...)` from `html/template`.
- Update any code that uses `text/template` to use `html/template` …
=> Potential fix for code scanning alert no. 2: Reflected cross-site scripting

httpclient/auth_flow_components.go, httpclient/authorization_code.go, httpclient/authorization_code_integration_test.go, httpclient/authorization_code_test.go, httpclient/browser_launcher.go, httpclient/browser_launcher_test.go, httpclient/client.go, httpclient/client_test.go, httpclient/response_validator.go, httpclient/response_validator_test.go, httpclient/server_manager.go, httpclient/server_manager_test.go, httpclient/url_builder.go, httpclient/url_builder_test.go, webflow/callback.go
- Added CallbackServerManager interface and DefaultCallbackServerManager implementation for managing OAuth callback servers.
- Introduced AuthorizationURLBuilder interface and DefaultAuthorizationURLBuilder for constructing authorization URLs.
- Created ResponseValidator interface and DefaultResponseValidator for validating OAuth callback responses.
- Implemented BrowserLauncher interface with DefaultBrowserLauncher for opening URLs in the default browser.
- Refactored Client to support dependency injection for authorization flow components.
- Added integration tests for the new components to ensure proper functionality and error handling.
=> feat: add auth code testability

httpclient/server_manager.go
The startCtx is being cancelled in such a way that the server listener for the auth code flow is shutdown prematurely. This is a temporary fix that disables the 5 minutes timeout on the server by simply using the outer ctx.
=> fix: startupCtx cancellation interrupts flow

httpclient/server_manager.go
- Corrected server startup timeout from 5 minutes to 2 seconds
- Server now runs with original context for full OAuth flow duration
- Startup detection context properly respects parent context cancellation
- Prevents server premature shutdown that caused "connection refused" errors
Fixes issue  where callback server would shut down immediately
after starting due to cancelled timeout context.
=> fix: separate startup detection timeout from server lifetime context

cmd/command_runner.go, cmd/token_exchange_cfg.go, cmd/token_exchange_cfg_test.go, httpclient/token.go, httpclient/token_test.go, oidc/token_exchange.go
This adds a token exchange command which can be used to execute the token exchange flow. Supports all token exchange parameters as specified in RFC8693. The subject token is mandatory and can be provided either on the command line or through stdin, similar to how the refresh token command has been implemented previously.
=> feature: support token exchange
